In [1]:
import pandas as pd
crime = pd.read_csv('Crime.csv', encoding = 'cp949')
crime

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,67,20,13,17,11,8,12,2,...,1,0,2,4,7,2,0,11,7,30
1,강력범죄,살인미수등,96,41,23,34,7,16,11,1,...,5,5,6,0,13,2,1,16,4,44
2,강력범죄,강도,274,161,60,103,44,64,29,0,...,1,4,2,13,26,3,4,29,4,65
3,강력범죄,강간,969,383,216,304,216,181,132,3,...,10,12,35,63,85,11,14,64,18,328
4,강력범죄,유사강간,118,24,21,35,17,14,10,1,...,1,1,3,1,8,1,1,12,0,33
5,강력범죄,강제추행,4282,991,645,924,495,362,293,34,...,20,22,59,58,172,36,32,165,28,764
6,강력범죄,기타강간강제추행등,94,37,20,31,22,12,9,0,...,1,2,1,4,13,3,1,11,2,55
7,강력범죄,방화,315,117,86,94,48,41,36,5,...,2,7,9,12,33,0,12,23,4,148
8,절도범죄,절도,55280,20136,12759,10679,8438,9495,5449,638,...,313,358,1205,2032,5860,602,921,3309,643,11754
9,폭력범죄,상해,7174,4675,2736,2179,1162,1516,1353,117,...,134,194,307,408,1187,321,269,532,149,3941
10,폭력범죄,폭행,36904,8852,6607,9774,5386,4054,4213,139,...,136,252,613,698,2650,319,570,1919,363,5712
11,폭력범죄,체포감금,186,67,39,81,26,36,20,3,...,0,2,10,10,17,5,3,9,4,87
12,폭력범죄,협박,1844,682,443,433,297,286,175,29,...,17,15,49,58,160,26,56,234,44,547
13,폭력범죄,약취유인,45,6,6,12,5,4,1,1,...,0,0,0,0,3,0,0,4,0,14
14,폭력범죄,폭력행위등,6725,2449,1595,1988,817,1045,906,71,...,82,78,144,202,669,138,145,383,95,2477
15,폭력범죄,공갈,634,558,263,222,118,94,79,4,...,9,0,16,19,87,11,8,37,26,178
16,폭력범죄,손괴,11735,3639,3019,3365,1791,1804,1530,88,...,105,129,323,286,1199,186,331,1018,144,3029
17,지능범죄,직무유기,106,37,25,14,22,20,10,16,...,0,2,2,5,5,2,0,7,2,62
18,지능범죄,직권남용,98,28,14,12,10,14,12,2,...,0,2,5,3,4,1,2,10,2,40
19,지능범죄,증수뢰,57,15,8,11,10,3,0,1,...,0,1,0,1,2,0,2,1,2,24
20,지능범죄,통화,801,75,84,121,30,72,17,1,...,1,2,2,6,12,2,2,14,4,61
21,지능범죄,문서인장,3336,1259,691,689,455,451,346,36,...,16,16,47,60,267,22,34,162,118,896
22,지능범죄,유가증권인지,125,5,9,14,3,4,3,2,...,0,0,0,0,0,0,0,0,2,12
23,지능범죄,사기,53879,20533,11507,13141,7669,7250,5606,487,...,431,601,1256,1441,6170,592,695,2734,2097,14465
24,지능범죄,횡령,13314,2980,1725,2763,1416,1216,794,122,...,51,52,180,165,708,74,122,439,235,1988
25,지능범죄,배임,1135,315,132,173,109,82,110,13,...,11,5,19,19,62,11,131,36,33,308
26,풍속범죄,성풍속범죄,5421,1164,933,1190,376,438,257,22,...,5,6,52,37,164,12,27,236,73,306
27,풍속범죄,도박범죄,1320,921,485,390,216,251,146,7,...,16,10,24,27,124,89,38,106,46,744
28,특별경제범죄,특별경제범죄,22075,13868,3421,5751,2535,1635,1289,187,...,109,145,310,399,1018,111,269,982,1631,3027
29,마약범죄,마약범죄,1360,759,393,557,69,78,67,2,...,43,24,25,90,122,10,6,20,16,509
30,보건범죄,보건범죄,3941,1832,417,654,760,204,230,15,...,51,29,57,123,258,19,37,131,36,843
31,환경범죄,환경범죄,53,198,19,69,8,13,53,2,...,19,18,7,20,77,21,24,22,30,503
32,교통범죄,교통범죄,74958,35841,39725,31163,23412,13556,16600,1056,...,1216,2517,3759,3351,12650,2936,3581,10857,2325,43877
33,노동범죄,노동범죄,215,190,31,28,13,14,63,0,...,0,1,10,0,19,43,3,6,1,45
34,안보범죄,안보범죄,38,4,4,20,3,4,2,0,...,1,0,0,1,1,0,0,0,1,6
35,선거범죄,선거범죄,24,24,18,19,9,8,15,5,...,4,5,3,30,17,4,12,11,3,267
36,병역범죄,병역범죄,4591,959,800,1200,371,630,382,86,...,57,42,158,92,355,52,52,190,155,808
37,기타범죄,기타범죄,41752,19868,9766,13677,5301,4602,4881,462,...,410,1040,978,933,3643,1594,1331,3130,1341,17797

In [2]:
crime.columns

Index(['범죄대분류', '범죄중분류', '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
       '경기 고양', '경기 과천', '경기 광명', '경기 광주', '경기 구리', '경기 군포', '경기 김포', '경기 남양주',
       '경기 동두천', '경기 부천', '경기 성남', '경기 수원', '경기 시흥', '경기 안산', '경기 안성', '경기 안양',
       '경기 양주', '경기 여주', '경기 오산', '경기 용인', '경기 의왕', '경기 의정부', '경기 이천', '경기 파주',
       '경기 평택', '경기 포천', '경기 하남', '경기 화성', '강원 강릉', '강원 동해', '강원 삼척', '강원 속초',
       '강원 원주', '강원 춘천', '강원 태백', '충북 제천', '충북 청주', '충북 충주', '충남 계룡', '충남 공주',
       '충남 논산', '충남 당진', '충남 보령', '충남 서산', '충남 아산', '충남 천안', '전북 군산', '전북 김제',
       '전북 남원', '전북 익산', '전북 전주', '전북 정읍', '전남 광양', '전남 나주', '전남 목포', '전남 순천',
       '전남 여수', '경북 경산', '경북 경주', '경북 구미', '경북 김천', '경북 문경', '경북 상주', '경북 안동',
       '경북 영주', '경북 영천', '경북 포항', '경남 거제', '경남 김해', '경남 마산', '경남 밀양', '경남 사천',
       '경남 양산', '경남 진주', '경남 창원', '경남 통영', '제주 서귀포', '제주 제주', '기타도시', '도시이외'],
      dtype='object')

In [3]:
col =  list(crime.iloc[:,1])
col

['살인기수',
 '살인미수등',
 '강도',
 '강간',
 '유사강간',
 '강제추행',
 '기타강간강제추행등',
 '방화',
 '절도',
 '상해',
 '폭행',
 '체포감금',
 '협박',
 '약취유인',
 '폭력행위등',
 '공갈',
 '손괴',
 '직무유기',
 '직권남용',
 '증수뢰',
 '통화',
 '문서인장',
 '유가증권인지',
 '사기',
 '횡령',
 '배임',
 '성풍속범죄',
 '도박범죄',
 '특별경제범죄',
 '마약범죄',
 '보건범죄',
 '환경범죄',
 '교통범죄',
 '노동범죄',
 '안보범죄',
 '선거범죄',
 '병역범죄',
 '기타범죄']

In [4]:
crime_df = crime.iloc[:,2:-2].T
crime_df.columns = col
crime_df.head(20)

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄
서울,67,96,274,969,118,4282,94,315,55280,7174,...,22075,1360,3941,53,74958,215,38,24,4591,41752
부산,20,41,161,383,24,991,37,117,20136,4675,...,13868,759,1832,198,35841,190,4,24,959,19868
대구,13,23,60,216,21,645,20,86,12759,2736,...,3421,393,417,19,39725,31,4,18,800,9766
인천,17,34,103,304,35,924,31,94,10679,2179,...,5751,557,654,69,31163,28,20,19,1200,13677
광주,11,7,44,216,17,495,22,48,8438,1162,...,2535,69,760,8,23412,13,3,9,371,5301
대전,8,16,64,181,14,362,12,41,9495,1516,...,1635,78,204,13,13556,14,4,8,630,4602
울산,12,11,29,132,10,293,9,36,5449,1353,...,1289,67,230,53,16600,63,2,15,382,4881
세종,2,1,0,3,1,34,0,5,638,117,...,187,2,15,2,1056,0,0,5,86,462
경기 고양,8,9,14,73,9,256,7,40,3287,490,...,1278,82,223,30,11926,13,1,4,360,3473
경기 과천,2,0,0,0,0,20,0,1,170,22,...,60,4,6,3,720,0,0,1,10,174
경기 광명,1,1,4,12,0,77,2,6,1234,147,...,818,15,90,2,2740,6,1,3,61,1138
경기 광주,4,8,4,25,3,49,2,6,1072,237,...,360,22,87,52,3660,13,0,0,170,1135
경기 구리,0,3,6,22,1,73,3,9,1042,181,...,299,16,62,9,2151,2,0,2,71,699
경기 군포,1,1,5,26,2,67,0,7,944,142,...,383,15,45,0,2121,4,0,0,53,672
경기 김포,2,3,7,33,5,75,2,13,1082,160,...,420,13,68,14,3726,4,0,3,50,1205
경기 남양주,5,6,12,50,2,132,9,26,1888,392,...,589,24,261,52,4795,6,0,0,312,2361
경기 동두천,0,3,0,6,0,36,0,1,410,102,...,107,25,20,5,954,0,0,0,44,372
경기 부천,7,13,25,105,12,291,7,38,5048,524,...,1449,56,162,14,10467,21,2,0,355,3804
경기 성남,4,6,30,83,12,319,14,29,3941,734,...,1749,79,244,4,8900,9,2,2,362,3297
경기 수원,6,7,38,157,21,425,23,40,6487,938,...,1596,118,368,25,14715,28,3,2,433,4856

In [5]:
crime_df.dropna()

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄
서울,67,96,274,969,118,4282,94,315,55280,7174,...,22075,1360,3941,53,74958,215,38,24,4591,41752
부산,20,41,161,383,24,991,37,117,20136,4675,...,13868,759,1832,198,35841,190,4,24,959,19868
대구,13,23,60,216,21,645,20,86,12759,2736,...,3421,393,417,19,39725,31,4,18,800,9766
인천,17,34,103,304,35,924,31,94,10679,2179,...,5751,557,654,69,31163,28,20,19,1200,13677
광주,11,7,44,216,17,495,22,48,8438,1162,...,2535,69,760,8,23412,13,3,9,371,5301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
경남 진주,4,0,13,63,1,58,4,12,2032,408,...,399,90,123,20,3351,0,1,30,92,933
경남 창원,7,13,26,85,8,172,13,33,5860,1187,...,1018,122,258,77,12650,19,1,17,355,3643
경남 통영,2,2,3,11,1,36,3,0,602,321,...,111,10,19,21,2936,43,0,4,52,1594
제주 서귀포,0,1,4,14,1,32,1,12,921,269,...,269,6,37,24,3581,3,0,12,52,1331
제주 제주,11,16,29,64,12,165,11,23,3309,532,...,982,20,131,22,10857,6,0,11,190,3130

In [6]:
crime_city = []
for i in crime_df.index:
    if i=='서울':
        i = '서울특별시'
    elif i =='세종':
        i= '세종특별자치시'
    elif len(i) == 2:
        i = i+ '광역시'
    else:
        i = i.split()[1]+'시'
    crime_city.append(i)
crime_city

['서울특별시',
 '부산광역시',
 '대구광역시',
 '인천광역시',
 '광주광역시',
 '대전광역시',
 '울산광역시',
 '세종특별자치시',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '여주시',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시',
 '강릉시',
 '동해시',
 '삼척시',
 '속초시',
 '원주시',
 '춘천시',
 '태백시',
 '제천시',
 '청주시',
 '충주시',
 '계룡시',
 '공주시',
 '논산시',
 '당진시',
 '보령시',
 '서산시',
 '아산시',
 '천안시',
 '군산시',
 '김제시',
 '남원시',
 '익산시',
 '전주시',
 '정읍시',
 '광양시',
 '나주시',
 '목포시',
 '순천시',
 '여수시',
 '경산시',
 '경주시',
 '구미시',
 '김천시',
 '문경시',
 '상주시',
 '안동시',
 '영주시',
 '영천시',
 '포항시',
 '거제시',
 '김해시',
 '마산시',
 '밀양시',
 '사천시',
 '양산시',
 '진주시',
 '창원시',
 '통영시',
 '서귀포시',
 '제주시']

In [7]:
crime_df['도시명'] = crime_city
crime_df

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄,도시명
서울,67,96,274,969,118,4282,94,315,55280,7174,...,1360,3941,53,74958,215,38,24,4591,41752,서울특별시
부산,20,41,161,383,24,991,37,117,20136,4675,...,759,1832,198,35841,190,4,24,959,19868,부산광역시
대구,13,23,60,216,21,645,20,86,12759,2736,...,393,417,19,39725,31,4,18,800,9766,대구광역시
인천,17,34,103,304,35,924,31,94,10679,2179,...,557,654,69,31163,28,20,19,1200,13677,인천광역시
광주,11,7,44,216,17,495,22,48,8438,1162,...,69,760,8,23412,13,3,9,371,5301,광주광역시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
경남 진주,4,0,13,63,1,58,4,12,2032,408,...,90,123,20,3351,0,1,30,92,933,진주시
경남 창원,7,13,26,85,8,172,13,33,5860,1187,...,122,258,77,12650,19,1,17,355,3643,창원시
경남 통영,2,2,3,11,1,36,3,0,602,321,...,10,19,21,2936,43,0,4,52,1594,통영시
제주 서귀포,0,1,4,14,1,32,1,12,921,269,...,6,37,24,3581,3,0,12,52,1331,서귀포시
제주 제주,11,16,29,64,12,165,11,23,3309,532,...,20,131,22,10857,6,0,11,190,3130,제주시

In [8]:
pop = pd.read_csv('pop.csv', encoding='cp949', header=2,).iloc[:,4:].T
pop

             0
서울특별시  9904312
종로구     161521
중구      128478
용산구     227282
성동구     295006
...        ...
읍부.14   129134
면부.14    31078
동부.14   445407
제주시     451758
서귀포시    153861

[323 rows x 1 columns]

In [9]:
cityName = pop.index
population = {}
for i in cityName:
    population[i]=int(pop.loc[i])
population.pop('세종시')
population

{'서울특별시': 9904312,
 '종로구': 161521,
 '중구': 128478,
 '용산구': 227282,
 '성동구': 295006,
 '광진구': 368199,
 '동대문구': 364787,
 '중랑구': 403237,
 '성북구': 456844,
 '강북구': 319992,
 '도봉구': 340095,
 '노원구': 562996,
 '은평구': 478374,
 '서대문구': 308768,
 '마포구': 381330,
 '양천구': 465512,
 '강서구': 570507,
 '구로구': 444832,
 '금천구': 250690,
 '영등포구': 406528,
 '동작구': 407894,
 '관악구': 519622,
 '서초구': 420804,
 '강남구': 541688,
 '송파구': 634941,
 '강동구': 444385,
 '부산광역시': 3448737,
 '읍부.1': 132088,
 '면부.1': 15985,
 '동부.1': 3300664,
 '중구.1': 45377,
 '서구': 111996,
 '동구': 89202,
 '영도구': 129515,
 '부산진구': 376321,
 '동래구': 262154,
 '남구': 283741,
 '북구': 299182,
 '해운대구': 409037,
 '사하구': 334762,
 '금정구': 249444,
 '강서구.1': 92628,
 '연제구': 203527,
 '수영구': 173069,
 '사상구': 240709,
 '기장군': 148073,
 '대구광역시': 2466052,
 '읍부.2': 138621,
 '면부.2': 51231,
 '동부.2': 2276200,
 '중구.2': 78334,
 '동구.1': 339608,
 '서구.1': 202963,
 '남구.1': 160164,
 '북구.1': 450579,
 '수성구': 437328,
 '달서구': 607224,
 '달성군': 189852,
 '인천광역시': 2890451,
 '읍부.3': 21089,
 '면부.3': 59844,
 '동부.3': 2809518,
 '중구.3': 112910,
 '동구.2': 71054,
 '남구.2': 405746,
 '연수구': 317172,
 '남동구': 527324,
 '부평구': 548461,
 '계양구': 327311,
 '서구.2': 499540,
 '강화군': 62291,
 '옹진군': 18642,
 '광주광역시': 1502881,
 '동구.3': 104173,
 '서구.3': 305512,
 '남구.3': 221759,
 '북구.2': 459715,
 '광산구': 411722,
 '대전광역시': 1538394,
 '동구.4': 247975,
 '중구.4': 250434,
 '서구.4': 491507,
 '유성구': 350015,
 '대덕구': 198463,
 '울산광역시': 1166615,
 '읍부.4': 154247,
 '면부.4': 68492,
 '동부.4': 943876,
 '중구.5': 236988,
 '남구.4': 341363,
 '동구.5': 176861,
 '북구.3': 188664,
 '울주군': 222739,
 '세종특별자치시': 204088,
 '읍부.5': 52834,
 '면부.5': 50155,
 '동부.5': 101099,
 '경기도': 12479061,
 '읍부.6': 1273396,
 '면부.6': 868833,
 '동부.6': 10336832,
 '수원시': 1194313,
 '장안구': 299611,
 '권선구': 349339,
 '팔달구': 208903,
 '영통구': 336460,
 '성남시': 948757,
 '수정구': 225967,
 '중원구': 244451,
 '분당구': 478339,
 '의정부시': 421579,
 '안양시': 585177,
 '만안구': 245305,
 '동안구': 339872,
 '부천시': 843794,
 '원미구': 440396,
 '소사구': 221553,
 '오정구': 181845,
 '광명시': 338509,
 '평택시': 457873,
 '동두천시': 97424,
 '안산시': 747035,
 '상록구': 383508,
 '단원구': 363527,
 '고양시': 990073,
 '덕양구': 425100,
 '일산동구': 277925,
 '일산서구': 287048,
 '과천시': 64817,
 '구리시': 180063,
 '남양주시': 629061,
 '오산시': 213840,
 '시흥시': 425184,
 '군포시': 285721,
 '의왕시': 154879,
 '하남시': 154838,
 '용인시': 971327,
 '처인구': 231892,
 '기흥구': 407238,
 '수지구': 332197,
 '파주시': 415345,
 '이천시': 209003,
 '안성시': 194765,
 '김포시': 352683,
 '화성시': 608725,
 '광주시': 310278,
 '양주시': 205988,
 '포천시': 163388,
 '여주시': 109937,
 '연천군': 43846,
 '가평군': 58909,
 '양평군': 101930,
 '강원도': 1518040,
 '읍부.7': 263480,
 '면부.7': 334016,
 '동부.7': 920544,
 '춘천시': 281596,
 '원주시': 330854,
 '강릉시': 215677,
 '동해시': 90255,
 '태백시': 46715,
 '속초시': 79846,
 '삼척시': 69509,
 '홍천군': 67190,
 '횡성군': 42669,
 '영월군': 36967,
 '평창군': 40427,
 '정선군': 36701,
 '철원군': 46025,
 '화천군': 25343,
 '양구군': 22497,
 '인제군': 31219,
 '고성군': 28689,
 '양양군': 25861,
 '충청북도': 1589347,
 '읍부.8': 309858,
 '면부.8': 328701,
 '동부.8': 950788,
 '충주시': 211005,
 '제천시': 136350,
 '청주시': 833276,
 '상당구': 171877,
 '서원구': 222721,
 '흥덕구': 255542,
 '청원구': 183136,
 '보은군': 32522,
 '옥천군': 50704,
 '영동군': 49542,
 '진천군': 71152,
 '괴산군': 37830,
 '음성군': 102023,
 '단양군': 28770,
 '증평군': 36173,
 '충청남도': 2107802,
 '읍부.9': 489361,
 '면부.9': 681198,
 '동부.9': 937243,
 '천안시': 629062,
 '동남구': 277781,
 '서북구': 351281,
 '공주시': 113542,
 '보령시': 101852,
 '아산시': 319929,
 '서산시': 169221,
 '논산시': 124246,
 '계룡시': 39243,
 '당진시': 163762,
 '금산군': 55923,
 '부여군': 69017,
 '서천군': 54768,
 '청양군': 31653,
 '홍성군': 94114,
 '예산군': 81747,
 '태안군': 59723,
 '전라북도': 1834114,
 '읍부.10': 156255,
 '면부.10': 380514,
 '동부.10': 1297345,
 '전주시': 658172,
 '완산구': 367243,
 '덕진구': 290929,
 '군산시': 275155,
 '익산시': 301723,
 '정읍시': 110627,
 '남원시': 80499,
 '김제시': 84269,
 '완주군': 95357,
 '진안군': 22886,
 '무주군': 23408,
 '장수군': 21620,
 '임실군': 25935,
 '순창군': 26707,
 '고창군': 55665,
 '부안군': 52091,
 '전라남도': 1799044,
 '읍부.11': 432653,
 '면부.11': 584676,
 '동부.11': 781715,
 '목포시': 239524,
 '여수시': 273761,
 '순천시': 265390,
 '나주시': 92582,
 '광양시': 144414,
 '담양군': 43634,
 '곡성군': 28617,
 '구례군': 24595,
 '고흥군': 62477,
 '보성군': 40688,
 '화순군': 61380,
 '장흥군': 36890,
 '강진군': 35126,
 '해남군': 69237,
 '영암군': 61535,
 '무안군': 80521,
 '함평군': 31367,
 '영광군': 51007,
 '장성군': 42058,
 '완도군': 48468,
 '진도군': 29538,
 '신안군': 36235,
 '경상북도': 2680294,
 '읍부.12': 605054,
 '면부.12': 635226,
 '동부.12': 1440014,
 '포항시': 511804,
 '남구.5': 243870,
 '북구.4': 267934,
 '경주시': 262310,
 '김천시': 137540,
 '안동시': 168581,
 '구미시': 421075,
 '영주시': 109266,
 '영천시': 97669,
 '상주시': 98760,
 '문경시': 71863,
 '경산시': 278500,
 '군위군': 22012,
 '의성군': 51021,
 '청송군': 24732,
 '영양군': 16781,
 '영덕군': 36539,
 '청도군': 41596,
 '고령군': 34117,
 '성주군': 41179,
 '칠곡군': 122462,
 '예천군': 42702,
 '봉화군': 31628,
 '울진군': 49387,
 '울릉군': 8770,
 '경상남도': 3334524,
 '읍부.13': 458732,
 '면부.13': 684929,
 '동부.13': 2190863,
 '진주시': 349788,
 '통영시': 137208,
 '사천시': 113335,
 '김해시': 534124,
 '밀양시': 103069,
 '거제시': 261371,
 '양산시': 297532,
 '창원시': 1059241,
 '의창구': 255200,
 '성산구': 234908,
 '마산합포구': 178945,
 '마산회원구': 208766,
 '진해구': 181422,
 '의령군': 27069,
 '함안군': 69355,
 '창녕군': 61635,
 '고성군.1': 53882,
 '남해군': 44248,
 '하동군': 44918,
 '산청군': 34034,
 '함양군': 38454,
 '거창군': 60464,
 '합천군': 44797,
 '제주특별자치도': 605619,
 '읍부.14': 129134,
 '면부.14': 31078,
 '동부.14': 445407,
 '제주시': 451758,
 '서귀포시': 153861}

In [10]:
city =  list(pop.index)
cityName = []
for j in city:
    if j[-1]=='시':
        cityName.append(j)


print(len(cityName))
print(len(crime_df.index))


for i in range(86):
    print(crime_df.index[i], cityName[i])

86
86
서울 서울특별시
부산 부산광역시
대구 대구광역시
인천 인천광역시
광주 광주광역시
대전 대전광역시
울산 울산광역시
세종 세종특별자치시
경기 고양 세종시
경기 과천 수원시
경기 광명 성남시
경기 광주 의정부시
경기 구리 안양시
경기 군포 부천시
경기 김포 광명시
경기 남양주 평택시
경기 동두천 동두천시
경기 부천 안산시
경기 성남 고양시
경기 수원 과천시
경기 시흥 구리시
경기 안산 남양주시
경기 안성 오산시
경기 안양 시흥시
경기 양주 군포시
경기 여주 의왕시
경기 오산 하남시
경기 용인 용인시
경기 의왕 파주시
경기 의정부 이천시
경기 이천 안성시
경기 파주 김포시
경기 평택 화성시
경기 포천 광주시
경기 하남 양주시
경기 화성 포천시
강원 강릉 여주시
강원 동해 춘천시
강원 삼척 원주시
강원 속초 강릉시
강원 원주 동해시
강원 춘천 태백시
강원 태백 속초시
충북 제천 삼척시
충북 청주 충주시
충북 충주 제천시
충남 계룡 청주시
충남 공주 천안시
충남 논산 공주시
충남 당진 보령시
충남 보령 아산시
충남 서산 서산시
충남 아산 논산시
충남 천안 계룡시
전북 군산 당진시
전북 김제 전주시
전북 남원 군산시
전북 익산 익산시
전북 전주 정읍시
전북 정읍 남원시
전남 광양 김제시
전남 나주 목포시
전남 목포 여수시
전남 순천 순천시
전남 여수 나주시
경북 경산 광양시
경북 경주 포항시
경북 구미 경주시
경북 김천 김천시
경북 문경 안동시
경북 상주 구미시
경북 안동 영주시
경북 영주 영천시
경북 영천 상주시
경북 포항 문경시
경남 거제 경산시
경남 김해 진주시
경남 마산 통영시
경남 밀양 사천시
경남 사천 김해시
경남 양산 밀양시
경남 진주 거제시
경남 창원 양산시
경남 통영 창원시
제주 서귀포 제주시
제주 제주 서귀포시

In [11]:
crime_df['인구'] = crime_df.도시명.map(population)
crime_df

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,보건범죄,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄,도시명,인구
서울,67,96,274,969,118,4282,94,315,55280,7174,...,3941,53,74958,215,38,24,4591,41752,서울특별시,9904312.0
부산,20,41,161,383,24,991,37,117,20136,4675,...,1832,198,35841,190,4,24,959,19868,부산광역시,3448737.0
대구,13,23,60,216,21,645,20,86,12759,2736,...,417,19,39725,31,4,18,800,9766,대구광역시,2466052.0
인천,17,34,103,304,35,924,31,94,10679,2179,...,654,69,31163,28,20,19,1200,13677,인천광역시,2890451.0
광주,11,7,44,216,17,495,22,48,8438,1162,...,760,8,23412,13,3,9,371,5301,광주광역시,1502881.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
경남 진주,4,0,13,63,1,58,4,12,2032,408,...,123,20,3351,0,1,30,92,933,진주시,349788.0
경남 창원,7,13,26,85,8,172,13,33,5860,1187,...,258,77,12650,19,1,17,355,3643,창원시,1059241.0
경남 통영,2,2,3,11,1,36,3,0,602,321,...,19,21,2936,43,0,4,52,1594,통영시,137208.0
제주 서귀포,0,1,4,14,1,32,1,12,921,269,...,37,24,3581,3,0,12,52,1331,서귀포시,153861.0
제주 제주,11,16,29,64,12,165,11,23,3309,532,...,131,22,10857,6,0,11,190,3130,제주시,451758.0

In [12]:
crime_item =  list(crime_df.columns)[:-2]
for i in crime_item:
    crime_df[i] = crime_df[i]/crime_df.인구
crime_df

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,보건범죄,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄,도시명,인구
서울,0.000007,0.000010,0.000028,0.000098,0.000012,0.000432,0.000009,0.000032,0.005581,0.000724,...,0.000398,0.000005,0.007568,0.000022,3.836713e-06,0.000002,0.000464,0.004216,서울특별시,9904312.0
부산,0.000006,0.000012,0.000047,0.000111,0.000007,0.000287,0.000011,0.000034,0.005839,0.001356,...,0.000531,0.000057,0.010393,0.000055,1.159845e-06,0.000007,0.000278,0.005761,부산광역시,3448737.0
대구,0.000005,0.000009,0.000024,0.000088,0.000009,0.000262,0.000008,0.000035,0.005174,0.001109,...,0.000169,0.000008,0.016109,0.000013,1.622026e-06,0.000007,0.000324,0.003960,대구광역시,2466052.0
인천,0.000006,0.000012,0.000036,0.000105,0.000012,0.000320,0.000011,0.000033,0.003695,0.000754,...,0.000226,0.000024,0.010781,0.000010,6.919335e-06,0.000007,0.000415,0.004732,인천광역시,2890451.0
광주,0.000007,0.000005,0.000029,0.000144,0.000011,0.000329,0.000015,0.000032,0.005615,0.000773,...,0.000506,0.000005,0.015578,0.000009,1.996166e-06,0.000006,0.000247,0.003527,광주광역시,1502881.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
경남 진주,0.000011,0.000000,0.000037,0.000180,0.000003,0.000166,0.000011,0.000034,0.005809,0.001166,...,0.000352,0.000057,0.009580,0.000000,2.858875e-06,0.000086,0.000263,0.002667,진주시,349788.0
경남 창원,0.000007,0.000012,0.000025,0.000080,0.000008,0.000162,0.000012,0.000031,0.005532,0.001121,...,0.000244,0.000073,0.011943,0.000018,9.440722e-07,0.000016,0.000335,0.003439,창원시,1059241.0
경남 통영,0.000015,0.000015,0.000022,0.000080,0.000007,0.000262,0.000022,0.000000,0.004387,0.002340,...,0.000138,0.000153,0.021398,0.000313,0.000000e+00,0.000029,0.000379,0.011617,통영시,137208.0
제주 서귀포,0.000000,0.000006,0.000026,0.000091,0.000006,0.000208,0.000006,0.000078,0.005986,0.001748,...,0.000240,0.000156,0.023274,0.000019,0.000000e+00,0.000078,0.000338,0.008651,서귀포시,153861.0
제주 제주,0.000024,0.000035,0.000064,0.000142,0.000027,0.000365,0.000024,0.000051,0.007325,0.001178,...,0.000290,0.000049,0.024033,0.000013,0.000000e+00,0.000024,0.000421,0.006928,제주시,451758.0

In [13]:
crime_df['성범죄'] =  crime_df.강간 + crime_df.유사강간 + crime_df.강제추행 + crime_df.기타강간강제추행등
crime_df

,살인기수,살인미수등,강도,강간,유사강간,강제추행,기타강간강제추행등,방화,절도,상해,...,환경범죄,교통범죄,노동범죄,안보범죄,선거범죄,병역범죄,기타범죄,도시명,인구,성범죄
서울,0.000007,0.000010,0.000028,0.000098,0.000012,0.000432,0.000009,0.000032,0.005581,0.000724,...,0.000005,0.007568,0.000022,3.836713e-06,0.000002,0.000464,0.004216,서울특별시,9904312.0,0.000552
부산,0.000006,0.000012,0.000047,0.000111,0.000007,0.000287,0.000011,0.000034,0.005839,0.001356,...,0.000057,0.010393,0.000055,1.159845e-06,0.000007,0.000278,0.005761,부산광역시,3448737.0,0.000416
대구,0.000005,0.000009,0.000024,0.000088,0.000009,0.000262,0.000008,0.000035,0.005174,0.001109,...,0.000008,0.016109,0.000013,1.622026e-06,0.000007,0.000324,0.003960,대구광역시,2466052.0,0.000366
인천,0.000006,0.000012,0.000036,0.000105,0.000012,0.000320,0.000011,0.000033,0.003695,0.000754,...,0.000024,0.010781,0.000010,6.919335e-06,0.000007,0.000415,0.004732,인천광역시,2890451.0,0.000448
광주,0.000007,0.000005,0.000029,0.000144,0.000011,0.000329,0.000015,0.000032,0.005615,0.000773,...,0.000005,0.015578,0.000009,1.996166e-06,0.000006,0.000247,0.003527,광주광역시,1502881.0,0.000499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
경남 진주,0.000011,0.000000,0.000037,0.000180,0.000003,0.000166,0.000011,0.000034,0.005809,0.001166,...,0.000057,0.009580,0.000000,2.858875e-06,0.000086,0.000263,0.002667,진주시,349788.0,0.000360
경남 창원,0.000007,0.000012,0.000025,0.000080,0.000008,0.000162,0.000012,0.000031,0.005532,0.001121,...,0.000073,0.011943,0.000018,9.440722e-07,0.000016,0.000335,0.003439,창원시,1059241.0,0.000262
경남 통영,0.000015,0.000015,0.000022,0.000080,0.000007,0.000262,0.000022,0.000000,0.004387,0.002340,...,0.000153,0.021398,0.000313,0.000000e+00,0.000029,0.000379,0.011617,통영시,137208.0,0.000372
제주 서귀포,0.000000,0.000006,0.000026,0.000091,0.000006,0.000208,0.000006,0.000078,0.005986,0.001748,...,0.000156,0.023274,0.000019,0.000000e+00,0.000078,0.000338,0.008651,서귀포시,153861.0,0.000312
제주 제주,0.000024,0.000035,0.000064,0.000142,0.000027,0.000365,0.000024,0.000051,0.007325,0.001178,...,0.000049,0.024033,0.000013,0.000000e+00,0.000024,0.000421,0.006928,제주시,451758.0,0.000558

In [14]:
crime_df.columns

Index(['살인기수', '살인미수등', '강도', '강간', '유사강간', '강제추행', '기타강간강제추행등', '방화', '절도',
       '상해', '폭행', '체포감금', '협박', '약취유인', '폭력행위등', '공갈', '손괴', '직무유기', '직권남용',
       '증수뢰', '통화', '문서인장', '유가증권인지', '사기', '횡령', '배임', '성풍속범죄', '도박범죄',
       '특별경제범죄', '마약범죄', '보건범죄', '환경범죄', '교통범죄', '노동범죄', '안보범죄', '선거범죄',
       '병역범죄', '기타범죄', '도시명', '인구', '성범죄'],
      dtype='object')

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x = crime_df[['살인기수', '살인미수등', '강도', '방화','폭행', '체포감금', '협박',\
             '약취유인', '폭력행위등', '공갈','공갈', '손괴', '직무유기', '직권남용',
       '증수뢰', '통화', '문서인장', '유가증권인지', '사기', '횡령', '배임', '성풍속범죄', '도박범죄',
       '특별경제범죄', '마약범죄', '보건범죄', '환경범죄', '교통범죄', '노동범죄', '안보범죄', '선거범죄',
       '병역범죄', '기타범죄']]
y = crime_df.성범죄
x_std = StandardScaler().fit_transform(x)
x_train, x_test, y_train, y_test = train_test_split(x_std, y, test_size = 0.3)

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
pred =  lr.predict(x_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
from sklearn.metrics import classification_report
report = classification_report(y_test, pred)
print(report)