In [1]:
with open('budongsan.csv', 'r', encoding='utf-8') as f:
    data = f.readlines()
    for line in data:
        print(line.replace('\n', '').split(',')[3:])

['주소', '부동산', '보증금', '월세']
['서울시 강남구 역삼동 0', 'TODAY공인중개사(이인규)', '1000.0', '100.0']
['서울시 강남구 역삼동 1', 'TODAY공인중개사(이인규)', '11000.0', '60.0']
['서울시 강남구 역삼동 2', '열린공인중개사(강광수)', '5000.0', '65.0']
['서울시 강남구 역삼동 3', '미래공인중개사(김유철)', '3000.0', '95.0']
['서울시 강남구 역삼동 4', '한백부동산공인중개사(김남조)', '110.0', '110.0']
['서울시 강남구 역삼동 5', '강남코리아공인중개사(기숙영)', '15000.0', '70.0']
['서울시 강남구 역삼동 6', '열린공인중개사(강광수)', '1000.0', '85.0']
['서울시 강남구 역삼동 7', '한강공인중개사(김상헌)', '1000.0', '80.0']
['서울시 강남구 역삼동 8', '동하공인중개사(임성우)', '1000.0', '60.0']
['서울시 강남구 역삼동 9', '스타공인중개사(박정직)', '2000.0', '50.0']
['서울시 강남구 역삼동 10', 'HS강남공인중개사(김현수)', '1000.0', '96.0']
['서울시 강남구 역삼동 11', 'H공인중개사(김용만)', '15000.0', '70.0']
['서울시 강남구 역삼동 12', '도원공인중개사(손석진)', '65.0', '65.0']
['서울시 강남구 역삼동 13', '강남우리공인중개사(어정화)', '2000.0', '150.0']
['서울시 강남구 역삼동 14', '청록공인중개사(하순자)', '3000.0', '60.0']
['서울시 강남구 역삼동 15', '커피한잔공인중개사(손별)', '500.0', '67.0']
['서울시 강남구 역삼동 16', '강남코리아공인중개사(기숙영)', '15000.0', '60.0']
['서울시 강남구 역삼동 17', 'TODAY공인중개사(이인규)', '5000.0', '50.0']
['서울시 강남구 역삼동 18', '나무공인중개사(조민영)', '90.0', '90.0']
['서울시 강남구 역삼동 19', '한강공인중개사(김상헌)', '300.0', '80.0']
['서울시 강남구 역삼동 20', 'TODAY공인중개사(이인규)', '5000.0', '60.0']
['서울시 강남구 역삼동 21', '한백부동산공인중개사(김남조)', '75.0', '75.0']
['서울시 강남구 역삼동 22', '강남코리아공인중개사(기숙영)', '1000.0', '65.0']
['서울시 강남구 역삼동 23', '도원공인중개사(손석진)', '65.0', '65.0']
['서울시 강남구 역삼동 24', 'TODAY공인중개사(이인규)', '1000.0', '60.0']
['서울시 강남구 역삼동 25', '아셈타운공인중개사(임현옥)', '7000.0', '100.0']
['서울시 강남구 역삼동 26', '강남코리아공인중개사(기숙영)', '2000.0', '63.0']
['서울시 강남구 역삼동 27', '웰컴공인중개사(이영진)', '1000.0', '120.0']
['서울시 강남구 역삼동 28', '건우공인중개사(김상모)', '70.0', '70.0']
['서울시 강남구 역삼동 29', 'NB공인중개사(길주현)', '1000.0', '70.0']
['서울시 강남구 역삼동 30', '부동산네트워크공인중개사(황창문)', '8000.0', '55.0']
['서울시 강남구 역삼동 31', '도원공인중개사(손석진)', '68.0', '68.0']
['서울시 강남구 역삼동 32', '스타공인중개사(박정직)', '4000.0', '40.0']
['서울시 강남구 역삼동 33', '대청공인중개사(이선영)', '14000.0', '70.0']
['서울시 강남구 역삼동 34', '한백부동산공인중개사(김남조)', '10000.0', '100.0']
['서울시 강남구 역삼동 35', '스타공인중개사(박정직)', '6000.0', '50.0']
['서울시 강남구 역삼동 36', '정성공인중개사(정문식)', '100.0', '100.0']
['서울시 강남구 역삼동 37', 'TODAY공인중개사(이인규)', '3000.0', '100.0']
['서울시 강남구 역삼동 38', '미래공인중개사(김유철)', '1000.0', '85.0']
['서울시 강남구 역삼동 39', '한백부동산공인중개사(김남조)', '75.0', '75.0']
['서울시 강남구 역삼동 40', '강남코리아공인중개사(기숙영)', '1000.0', '63.0']
['서울시 강남구 역삼동 41', '친절한공인중개사(김천호)', '500.0', '65.0']
['서울시 강남구 역삼동 42', '강남코리아공인중개사(기숙영)', '3000.0', '75.0']

In [2]:
import pandas as pd
bd = pd.read_csv('budongsan.csv')[['매물번호', '연락처', '주소', '부동산', '보증금', '월세']]
bd[(bd.월세<=60)]
bd[(bd.월세<=60) & (bd.보증금<=1000)]
bd[(bd.보증금<=1000)]
bd[bd.보증금<=500].월세.min()
bd.loc[ bd[bd.보증금<=500].월세.idxmin() ]

매물번호        3.2494e+06
연락처       010-123-4567
주소      서울시 강남구 역삼동 12
부동산       도원공인중개사(손석진)
보증금                 65
월세                  65
Name: 12, dtype: object

In [3]:
bd.보증금

0      1000.0
1     11000.0
2      5000.0
3      3000.0
4       110.0
5     15000.0
6      1000.0
7      1000.0
8      1000.0
9      2000.0
10     1000.0
11    15000.0
12       65.0
13     2000.0
14     3000.0
15      500.0
16    15000.0
17     5000.0
18       90.0
19      300.0
20     5000.0
21       75.0
22     1000.0
23       65.0
24     1000.0
25     7000.0
26     2000.0
27     1000.0
28       70.0
29     1000.0
30     8000.0
31       68.0
32     4000.0
33    14000.0
34    10000.0
35     6000.0
36      100.0
37     3000.0
38     1000.0
39       75.0
40     1000.0
41      500.0
42     3000.0
Name: 보증금, dtype: float64

In [4]:
bd['업자']= bd.부동산.apply(lambda x: x.split('(')[1].replace(')', '') )
bd = bd.drop('연락처', axis=1)

In [5]:
bd['부동산'] = bd.부동산.apply(lambda x: x.split('(')[0].replace('공인중개사', '') )
bd

         매물번호              주소      부동산      보증금     월세   업자
0   3467204.0   서울시 강남구 역삼동 0    TODAY   1000.0  100.0  이인규
1   3150497.0   서울시 강남구 역삼동 1    TODAY  11000.0   60.0  이인규
2   3440906.0   서울시 강남구 역삼동 2       열린   5000.0   65.0  강광수
3   3376834.0   서울시 강남구 역삼동 3       미래   3000.0   95.0  김유철
4   3331511.0   서울시 강남구 역삼동 4    한백부동산    110.0  110.0  김남조
5   3373198.0   서울시 강남구 역삼동 5    강남코리아  15000.0   70.0  기숙영
6   3376434.0   서울시 강남구 역삼동 6       열린   1000.0   85.0  강광수
7   3322860.0   서울시 강남구 역삼동 7       한강   1000.0   80.0  김상헌
8   3303061.0   서울시 강남구 역삼동 8       동하   1000.0   60.0  임성우
9   3262172.0   서울시 강남구 역삼동 9       스타   2000.0   50.0  박정직
10  3228631.0  서울시 강남구 역삼동 10     HS강남   1000.0   96.0  김현수
11  3505011.0  서울시 강남구 역삼동 11        H  15000.0   70.0  김용만
12  3249401.0  서울시 강남구 역삼동 12       도원     65.0   65.0  손석진
13  3330951.0  서울시 강남구 역삼동 13     강남우리   2000.0  150.0  어정화
14  3494055.0  서울시 강남구 역삼동 14       청록   3000.0   60.0  하순자
15  3317227.0  서울시 강남구 역삼동 15     커피한잔    500.0   67.0   손별
16  3405679.0  서울시 강남구 역삼동 16    강남코리아  15000.0   60.0  기숙영
17  3103384.0  서울시 강남구 역삼동 17    TODAY   5000.0   50.0  이인규
18  3418616.0  서울시 강남구 역삼동 18       나무     90.0   90.0  조민영
19  3456814.0  서울시 강남구 역삼동 19       한강    300.0   80.0  김상헌
20  3181675.0  서울시 강남구 역삼동 20    TODAY   5000.0   60.0  이인규
21  3309372.0  서울시 강남구 역삼동 21    한백부동산     75.0   75.0  김남조
22  3501566.0  서울시 강남구 역삼동 22    강남코리아   1000.0   65.0  기숙영
23  3346510.0  서울시 강남구 역삼동 23       도원     65.0   65.0  손석진
24  3406670.0  서울시 강남구 역삼동 24    TODAY   1000.0   60.0  이인규
25  3493254.0  서울시 강남구 역삼동 25     아셈타운   7000.0  100.0  임현옥
26  3501607.0  서울시 강남구 역삼동 26    강남코리아   2000.0   63.0  기숙영
27  3484623.0  서울시 강남구 역삼동 27       웰컴   1000.0  120.0  이영진
28  3190410.0  서울시 강남구 역삼동 28       건우     70.0   70.0  김상모
29  3350050.0  서울시 강남구 역삼동 29       NB   1000.0   70.0  길주현
30  3495453.0  서울시 강남구 역삼동 30  부동산네트워크   8000.0   55.0  황창문
31  3446619.0  서울시 강남구 역삼동 31       도원     68.0   68.0  손석진
32  3451078.0  서울시 강남구 역삼동 32       스타   4000.0   40.0  박정직
33  3345445.0  서울시 강남구 역삼동 33       대청  14000.0   70.0  이선영
34  3332380.0  서울시 강남구 역삼동 34    한백부동산  10000.0  100.0  김남조
35  3450803.0  서울시 강남구 역삼동 35       스타   6000.0   50.0  박정직
36  3471049.0  서울시 강남구 역삼동 36       정성    100.0  100.0  정문식
37  3438747.0  서울시 강남구 역삼동 37    TODAY   3000.0  100.0  이인규
38  3330749.0  서울시 강남구 역삼동 38       미래   1000.0   85.0  김유철
39  3446920.0  서울시 강남구 역삼동 39    한백부동산     75.0   75.0  김남조
40  3501554.0  서울시 강남구 역삼동 40    강남코리아   1000.0   63.0  기숙영
41  3435418.0  서울시 강남구 역삼동 41      친절한    500.0   65.0  김천호
42  3501551.0  서울시 강남구 역삼동 42    강남코리아   3000.0   75.0  기숙영

In [6]:
bd['주소'] = bd.주소.apply(lambda x: x.split()[2]+x.split()[3])
bd

         매물번호     주소      부동산      보증금     월세   업자
0   3467204.0   역삼동0    TODAY   1000.0  100.0  이인규
1   3150497.0   역삼동1    TODAY  11000.0   60.0  이인규
2   3440906.0   역삼동2       열린   5000.0   65.0  강광수
3   3376834.0   역삼동3       미래   3000.0   95.0  김유철
4   3331511.0   역삼동4    한백부동산    110.0  110.0  김남조
5   3373198.0   역삼동5    강남코리아  15000.0   70.0  기숙영
6   3376434.0   역삼동6       열린   1000.0   85.0  강광수
7   3322860.0   역삼동7       한강   1000.0   80.0  김상헌
8   3303061.0   역삼동8       동하   1000.0   60.0  임성우
9   3262172.0   역삼동9       스타   2000.0   50.0  박정직
10  3228631.0  역삼동10     HS강남   1000.0   96.0  김현수
11  3505011.0  역삼동11        H  15000.0   70.0  김용만
12  3249401.0  역삼동12       도원     65.0   65.0  손석진
13  3330951.0  역삼동13     강남우리   2000.0  150.0  어정화
14  3494055.0  역삼동14       청록   3000.0   60.0  하순자
15  3317227.0  역삼동15     커피한잔    500.0   67.0   손별
16  3405679.0  역삼동16    강남코리아  15000.0   60.0  기숙영
17  3103384.0  역삼동17    TODAY   5000.0   50.0  이인규
18  3418616.0  역삼동18       나무     90.0   90.0  조민영
19  3456814.0  역삼동19       한강    300.0   80.0  김상헌
20  3181675.0  역삼동20    TODAY   5000.0   60.0  이인규
21  3309372.0  역삼동21    한백부동산     75.0   75.0  김남조
22  3501566.0  역삼동22    강남코리아   1000.0   65.0  기숙영
23  3346510.0  역삼동23       도원     65.0   65.0  손석진
24  3406670.0  역삼동24    TODAY   1000.0   60.0  이인규
25  3493254.0  역삼동25     아셈타운   7000.0  100.0  임현옥
26  3501607.0  역삼동26    강남코리아   2000.0   63.0  기숙영
27  3484623.0  역삼동27       웰컴   1000.0  120.0  이영진
28  3190410.0  역삼동28       건우     70.0   70.0  김상모
29  3350050.0  역삼동29       NB   1000.0   70.0  길주현
30  3495453.0  역삼동30  부동산네트워크   8000.0   55.0  황창문
31  3446619.0  역삼동31       도원     68.0   68.0  손석진
32  3451078.0  역삼동32       스타   4000.0   40.0  박정직
33  3345445.0  역삼동33       대청  14000.0   70.0  이선영
34  3332380.0  역삼동34    한백부동산  10000.0  100.0  김남조
35  3450803.0  역삼동35       스타   6000.0   50.0  박정직
36  3471049.0  역삼동36       정성    100.0  100.0  정문식
37  3438747.0  역삼동37    TODAY   3000.0  100.0  이인규
38  3330749.0  역삼동38       미래   1000.0   85.0  김유철
39  3446920.0  역삼동39    한백부동산     75.0   75.0  김남조
40  3501554.0  역삼동40    강남코리아   1000.0   63.0  기숙영
41  3435418.0  역삼동41      친절한    500.0   65.0  김천호
42  3501551.0  역삼동42    강남코리아   3000.0   75.0  기숙영

In [8]:
bd.sort_values('보증금').head()

         매물번호     주소    부동산   보증금    월세   업자
12  3249401.0  역삼동12     도원  65.0  65.0  손석진
23  3346510.0  역삼동23     도원  65.0  65.0  손석진
31  3446619.0  역삼동31     도원  68.0  68.0  손석진
28  3190410.0  역삼동28     건우  70.0  70.0  김상모
21  3309372.0  역삼동21  한백부동산  75.0  75.0  김남조

In [11]:
bd = bd[['매물번호', '주소', '부동산', '업자', '보증금', '월세']]
bd['예상전세'] = bd.보증금+bd.월세*100
bd

         매물번호     주소      부동산   업자      보증금     월세     예상전세
0   3467204.0   역삼동0    TODAY  이인규   1000.0  100.0  11000.0
1   3150497.0   역삼동1    TODAY  이인규  11000.0   60.0  17000.0
2   3440906.0   역삼동2       열린  강광수   5000.0   65.0  11500.0
3   3376834.0   역삼동3       미래  김유철   3000.0   95.0  12500.0
4   3331511.0   역삼동4    한백부동산  김남조    110.0  110.0  11110.0
5   3373198.0   역삼동5    강남코리아  기숙영  15000.0   70.0  22000.0
6   3376434.0   역삼동6       열린  강광수   1000.0   85.0   9500.0
7   3322860.0   역삼동7       한강  김상헌   1000.0   80.0   9000.0
8   3303061.0   역삼동8       동하  임성우   1000.0   60.0   7000.0
9   3262172.0   역삼동9       스타  박정직   2000.0   50.0   7000.0
10  3228631.0  역삼동10     HS강남  김현수   1000.0   96.0  10600.0
11  3505011.0  역삼동11        H  김용만  15000.0   70.0  22000.0
12  3249401.0  역삼동12       도원  손석진     65.0   65.0   6565.0
13  3330951.0  역삼동13     강남우리  어정화   2000.0  150.0  17000.0
14  3494055.0  역삼동14       청록  하순자   3000.0   60.0   9000.0
15  3317227.0  역삼동15     커피한잔   손별    500.0   67.0   7200.0
16  3405679.0  역삼동16    강남코리아  기숙영  15000.0   60.0  21000.0
17  3103384.0  역삼동17    TODAY  이인규   5000.0   50.0  10000.0
18  3418616.0  역삼동18       나무  조민영     90.0   90.0   9090.0
19  3456814.0  역삼동19       한강  김상헌    300.0   80.0   8300.0
20  3181675.0  역삼동20    TODAY  이인규   5000.0   60.0  11000.0
21  3309372.0  역삼동21    한백부동산  김남조     75.0   75.0   7575.0
22  3501566.0  역삼동22    강남코리아  기숙영   1000.0   65.0   7500.0
23  3346510.0  역삼동23       도원  손석진     65.0   65.0   6565.0
24  3406670.0  역삼동24    TODAY  이인규   1000.0   60.0   7000.0
25  3493254.0  역삼동25     아셈타운  임현옥   7000.0  100.0  17000.0
26  3501607.0  역삼동26    강남코리아  기숙영   2000.0   63.0   8300.0
27  3484623.0  역삼동27       웰컴  이영진   1000.0  120.0  13000.0
28  3190410.0  역삼동28       건우  김상모     70.0   70.0   7070.0
29  3350050.0  역삼동29       NB  길주현   1000.0   70.0   8000.0
30  3495453.0  역삼동30  부동산네트워크  황창문   8000.0   55.0  13500.0
31  3446619.0  역삼동31       도원  손석진     68.0   68.0   6868.0
32  3451078.0  역삼동32       스타  박정직   4000.0   40.0   8000.0
33  3345445.0  역삼동33       대청  이선영  14000.0   70.0  21000.0
34  3332380.0  역삼동34    한백부동산  김남조  10000.0  100.0  20000.0
35  3450803.0  역삼동35       스타  박정직   6000.0   50.0  11000.0
36  3471049.0  역삼동36       정성  정문식    100.0  100.0  10100.0
37  3438747.0  역삼동37    TODAY  이인규   3000.0  100.0  13000.0
38  3330749.0  역삼동38       미래  김유철   1000.0   85.0   9500.0
39  3446920.0  역삼동39    한백부동산  김남조     75.0   75.0   7575.0
40  3501554.0  역삼동40    강남코리아  기숙영   1000.0   63.0   7300.0
41  3435418.0  역삼동41      친절한  김천호    500.0   65.0   7000.0
42  3501551.0  역삼동42    강남코리아  기숙영   3000.0   75.0  10500.0

0      역삼동0
1      역삼동1
2      역삼동2
3      역삼동3
4      역삼동4
5      역삼동5
6      역삼동6
7      역삼동7
8      역삼동8
9      역삼동9
10    역삼동10
11    역삼동11
12    역삼동12
13    역삼동13
14    역삼동14
15    역삼동15
16    역삼동16
17    역삼동17
18    역삼동18
19    역삼동19
20    역삼동20
21    역삼동21
22    역삼동22
23    역삼동23
24    역삼동24
25    역삼동25
26    역삼동26
27    역삼동27
28    역삼동28
29    역삼동29
30    역삼동30
31    역삼동31
32    역삼동32
33    역삼동33
34    역삼동34
35    역삼동35
36    역삼동36
37    역삼동37
38    역삼동38
39    역삼동39
40    역삼동40
41    역삼동41
42    역삼동42
Name: 주소, dtype: object